### PR TITLE
fix target container image

### PR DESCRIPTION
**Pull request by curx**
@alexellis should the target version set to 0.3.6 or 0.3.y

### CODE REVIEW

**Comment by alexellis** [comment]
Need a bit more info from you 🤓

**Comment by curx** [comment]
at line 339, of the README: 
"Now we can push a new version of the expressjs-k8s Docker image, i.e. from version alexellis2/service:0.3.5 to alexellis2/service:0.3.5"

Should the new version not be increased?

**Review by alexellis — APPROVED** [review]
Looks good

**Comment by alexellis** [comment]
You're right. Thanks for clarifying

**Pull request merged**
